[workspace]
members = ["cdis-assemble", "cdis-gateway", "dis-rs"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.74"
license = "MIT"
authors = ["Zeeger Lubsen <zeeger@lubsen.eu>"]
repository = "https://github.com/zlubsen/dis-rs"
categories = ["network-programming"]
