[package]
name = "udp_dis_read_and_write"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
gateway-core = { path = "../../gateway-core" }
dis-rs = { path = "../../dis-rs" }
tokio = "1.48.0"
