# Metadata allows the user to specify a name and versioning for the configuration
[metadata]
name = "Test Config for Localhost"
author = "zlubsen"
version = "0.1"

# The mode of the gateway is either "full_update" or "partial_update"; Optional value, defaults to FullUpdate mode
update_mode = "full_update"
#update_mode = "partial_update"

# The `[dis]` entry specifies the endpoint (interface and remote address) for receiving/sending DIS PDUs
[dis]
# `uri` specifies the remote address where to send and receive PDUs from. Format is "<IPv4_address>:<port>" for IPv4 or "[<IPv6_address>]:<port>". Mandatory field.
uri = "127.0.0.1:3000"
#uri = "[::1]:3000"
# `interface` specifies the interface which to bind the gateway to. Outgoing packets are send via this interface. Format is "<IP_of_the_interface>:<port>". Mandatory field.
interface = "127.0.0.1:3000"
#uri = "[::1]:3000"
# `mode` specifies the type of connection, being `unicast`, `broadcast`, or `multicast`. Optional, defaults to `unicast`.
mode = "unicast"
#mode = "broadcast"
#mode = "multicast"
# `ttl` specifies the time-to-live of packets send by the gateway via this endpoint. Optional, defaults to '1'.
ttl = 1
# 'block_own_host' specifies whether the endpoint will block incoming messages that originate from the 'interface' socket address, to avoid echoing its own messages. It takes a boolean value, `true` or `false`. Optional, defaults to `true`.
block_own_host = true

# The [cdis] entry specifies the endpoint (interface and remote address) for receiving/sending DIS PDUs
[cdis]
# `uri` specifies the remote address where to send and receive PDUs from. Format is "<IP_of_the_address>:<port>". Mandatory field.
uri = "127.0.0.1:3001"
# `interface` specifies the interface which to bind the gateway to. Outgoing packets are send via this interface. Format is "<IP_of_the_interface>:<port>". Mandatory field.
interface = "127.0.0.1:3001"
# `mode` specifies the type of connection, being `unicast`, `broadcast`, or `multicast`. Optional value, defaults to `unicast`.
mode = "unicast"
# `ttl` specifies the time-to-live of packets send by the gateway via this endpoint.
ttl = 1
# `block_own_host` specifies whether the endpoint will block incoming messages that originate from the 'interface' socket address, to avoid echoing its own messages. It takes a boolean value, `true` or `false`. Optional, defaults to `true`.
block_own_host = true

# The `templates` entry specifies where the monitoring dashboard of the gateway is hosted.
[site]
# `port` specifies the port on the host where the templates is hosted. It defaults to port 8080.
port = 8080

# The `encoder` entry specifies settings for the encoding/decoding of PDUs.
[encoder]
# `optimization` sets the type of processing the gateway will optimize for. The field takes a string value, either "bandwidth" or "completeness".
# Optional value.
# In practice, optimizing for `bandwidth` means that the EntityState PDU fields 'DR Other Parameters' and 'Capabilities' are never encoded and transmitted over C-DIS.
optimization = "completeness"

# The `federation` entry specifies DIS Federation Agreements on timeouts, heartbeat timers.
[federation]
# `hbt_cdis_full_update_mplier` sets the CDIS heartbeat full update multiplier. Optional field. Float value. Defaults to 2.4.
hbt_cdis_full_update_mplier = 2.4
# hbt_espdu_kind_cultural_feature # Default: 5 s
# hbt_espdu_kind_environmental # Default: 5 s
# hbt_espdu_kind_expendable # Default: 5 s
# hbt_espdu_kind_life_form # Default: 5 s
# hbt_espdu_kind_munition # Default: 5 s
# hbt_espdu_kind_radio # Default: 5 s
# hbt_espdu_kind_sensor # Default: 5 s
# hbt_espdu_kind_emitter # Default: 5 s
# hbt_espdu_kind_supply # Default: 5 s
# hbt_espdu_platform_air # Default: 5 s
# hbt_espdu_platform_land # Default: 5 s
# hbt_espdu_platform_space # Default: 5 s
# hbt_espdu_platform_subsurface # Default: 5 s
# hbt_espdu_platform_surface # Default: 5 s
# hbt_pdu_designator # Default: 5 s
# hbt_pdu_ee # Default: 5 s
# hbt_pdu_iff # Default: 10 s
# hbt_pdu_transmitter # Default: 2 s
# hbt_stationary # Default: 1 min
# hbt_timeout_mplier # Default: 2.4 (see NOTE 2)
